---
- name: Create cloudadmins group
  group:
    name: cloudadmins
    state: present

- name: Ensure wheel group exists
  group:
    name: wheel
    state: present

- name: Create user accounts
  user:
    name: "{{ item }}"
    groups: "cloudadmins,wheel"
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: ".ssh/id_rsa"
  loop: "{{ users }}"

- name: Fetch user100 private key
  fetch:
    src: "/home/user100/.ssh/id_rsa"
    dest: "~/.ssh/user100_key"
    flat: yes
    mode: '0600'
  become: yes
  when: inventory_hostname == groups['linux_vms'][0]