---
- name: Install Apache
  package:
    name: apache2
    state: present

- name: Create and deploy index.html directly on each VM
  copy:
    content: "{{ fqdn }}"
    dest: /var/www/html/index.html
    mode: '0444'
  notify: restart apache2

- name: Ensure Apache is enabled and started
  service:
    name: apache2
    state: started
    enabled: yes