---
- name: Append lines to /etc/profile
  blockinfile:
    path: /etc/profile
    block: |
      #Test block added by Ansible......Malan
      export TMOUT=1500
    marker: "# {mark} ANSIBLE MANAGED BLOCK - n01639496"